language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - "5.0"
services:
  - mongodb
install:
  - npm install
  - npm install coveralls
before_script:
  - npm install -g gulp
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - mocha spec/*
  - gulp test:fend
after_success:
  - npm run coveralls
sudo: false
