language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - "5.0"
services:
  - mongodb
install:
  - npm install
  - npm install coveralls
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g mocha
  - npm install -g gulp
script:
  - npm test
  - gulp test:fend
after_success:
  - npm run BendCoverage
  - npm run FendCoverage
sudo: false

deploy:
  provider: heroku
  api_key:
    secure: 04c947b8-e44c-4684-9cf3-d0ce5f8d6553
  app: doccy
